# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [ ]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [ ]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

In [11]:
import numpy as np

vet1 = np.arange(1000000)
vet2 = list(range(1000000))

%time for _ in range(10): res1 = vet1 * 2
%time for _ in range(10): res2 = [x * 2 for x in vet2]

Wall time: 9.97 ms
Wall time: 501 ms


### Exercício 2

In [ ]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

In [13]:
import numpy as np

vet1 = np.arange(10)
vet1[5:8] = 0
print(vet1)

[0 1 2 3 4 0 0 0 8 9]


### Exercício 3

In [ ]:
# Crie um array de 3 dimensões e imprima a dimensão 1 

In [19]:
import numpy as np

vet3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(vet3[1])


[4 5 6]


### Exercício 4

In [ ]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

In [29]:
import numpy as np

vet4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(vet4[2])
print(vet4[:2,1:])

[7 8 9]
[[2 3]
 [5 6]]


### Exercício 5

In [31]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
print(np.array(arr).T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### Exercício 6

In [ ]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [58]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

resultado = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
resultado

[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [ ]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

In [ ]:
A = np.arange(10)
np.save('array_a', A)

B = np.load('array_a.npy')
print(B)

### Exercício 8

In [ ]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [59]:
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

unico = obj.unique()
unico

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [18]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [60]:
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

data = resp.json()
data[0]['title']

issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

number                                              title  \
0    48125  BUG: #39448 fixed dropna to return copy correctly   
1    48124  BUG: using NamedTuples with .loc works only so...   
2    48123  BUG: inconsistent behaviour of the method `.id...   
3    48122  BUG: Parsing ISO 8601 duration time components...   
4    48120                                              1.4.x   
5    48119                   WEB: Update inactive maintainers   
6    48118  DOC: GH48097 remove optional from data for Dat...   
7    48117                        ENH: droplevel copy keyword   
8    48116  Revert Interval/IntervalIndex/interval_range.i...   
9    48115                   DEPR: inplace kwarg in set_index   
10   48113   DOC: update contributing to pandas documentation   
11   48111                  ENH: Add cumulative methods to ea   
12   48110  ENH: dtype-unaware (empty) objects ("any" dtype)    
13   48109                        ENH: Support mask in unique   
14   48108                            DEV: add gitpod actions   
15   48107                              DEV: Add gitpod files   
16   48103  BUG: timedelta as value to plot barplot raises...   
17   48101  DOC: `is_float_dtype` meant to be an internal ...   
18   48100  DOC: Altered capitalization validation script ...   
19   48097  DOC: DatetimeIndex says that data is optional,...   
20   48093       TST: Filter/test pyarrow PerformanceWarnings   
21   48091                                              QST:    
22   48090  BUG: DataFrame.select_dtypes returns reference...   
23   48088  ENH: move an exception and add a prehook to ch...   
24   48086  ENH: add `regex=False` option to pandas.Series...   
25   48085  ENH: Add axis parameter to add_prefix and add_...   
26   48084  ENH: alleviate issues with inconsistent multi-...   
27   48083  BUG: pd.cut creates NaNs instead of expected b...   
28   48080     PDEP-3: Small data visualization consolidation   
29   48078         ENH: Support mask for groupby var and mean   

                                               labels state  
0                                                  []  open  
1   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
2   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
3   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
4   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
5   [{'id': 32933285, 'node_id': 'MDU6TGFiZWwzMjkz...  open  
6                                                  []  open  
7                                                  []  open  
8   [{'id': 150096370, 'node_id': 'MDU6TGFiZWwxNTA...  open  
9                                                  []  open  
10  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
11  [{'id': 1817503692, 'node_id': 'MDU6TGFiZWwxOD...  open  
12  [{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...  open  
13  [{'id': 57296398, 'node_id': 'MDU6TGFiZWw1NzI5...  open  
14  [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...  open  
15  [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...  open  
16  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
17  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
18  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
19  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
20  [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
21  [{'id': 34444536, 'node_id': 'MDU6TGFiZWwzNDQ0...  open  
22  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
23  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
24  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
25  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
26  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
27  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
28  [{'id': 2301354, 'node_id': 'MDU6TGFiZWwyMzAxM...  open  
29  [{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...  open

### Exercício 10

In [ ]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

In [ ]:
import sqlite3
import pandas as pd
query = """
CREATE TABLE TESTE
(Cidade VARCHAR(20), 
 Estado VARCHAR(20),
 taxa REAL,        
 Impostos INTEGER
);"""
con = sqlite3.connect('dsa.db')
con.execute(query)
con.commit()

data = [('Natal', 'Rio Grande do Norte', 1.25, 6),
        ('Recife', 'Pernambuco', 2.6, 3),
        ('Londrina', 'Paraná', 1.7, 5)]
stmt = "INSERT INTO TESTE VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

cursor = con.execute('select * from teste')
rows = cursor.fetchall()
rows


cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

# Fim


### Obrigado

### Visite o Blog da Data Science Academy - <a href="http://blog.dsacademy.com.br">Blog DSA</a>
